//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kzrnm.TwitterJikkyo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kzrnm.TwitterJikkyo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   次のアカウントを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivateNextAccount {
            get {
                return ResourceManager.GetString("ActivateNextAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次の画像アカウントを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivateNextImageAccount {
            get {
                return ResourceManager.GetString("ActivateNextImageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前のアカウントを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivatePreviousAccount {
            get {
                return ResourceManager.GetString("ActivatePreviousAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前の画像アカウントを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActivatePreviousImageAccount {
            get {
                return ResourceManager.GetString("ActivatePreviousImageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureScreenshot {
            get {
                return ResourceManager.GetString("CaptureScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedToPost {
            get {
                return ResourceManager.GetString("FailedToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿に失敗しました
        ///元に戻ししますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedToPostMessage {
            get {
                return ResourceManager.GetString("FailedToPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像投稿アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImagePostingAccount {
            get {
                return ResourceManager.GetString("ImagePostingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リプライ先を指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputInReplyTo {
            get {
                return ResourceManager.GetString("InputInReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リプライ先のURLまたはIDを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputInReplyToMessage {
            get {
                return ResourceManager.GetString("InputInReplyToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   常に最前面に表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsTopmostSetting {
            get {
                return ResourceManager.GetString("IsTopmostSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TwitterJikkyo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー画面をここに移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MovePreviewWindowHere {
            get {
                return ResourceManager.GetString("MovePreviewWindowHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインしていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PIN コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Post に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostContent {
            get {
                return ResourceManager.GetString("PostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostingAccount {
            get {
                return ResourceManager.GetString("PostingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POSTキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostKey {
            get {
                return ResourceManager.GetString("PostKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RestoreDefaultConfig {
            get {
                return ResourceManager.GetString("RestoreDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハッシュタグ ON/OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleHashtag {
            get {
                return ResourceManager.GetString("ToggleHashtag", resourceCulture);
            }
        }
    }
}
