//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kzrnm.TwitterJikkyo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kzrnm.TwitterJikkyo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャプチャする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureScreenshot {
            get {
                return ResourceManager.GetString("CaptureScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   常に最前面に表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsTopmostSetting {
            get {
                return ResourceManager.GetString("IsTopmostSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TwitterJikkyo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー画面をここに移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MovePreviewWindowHere {
            get {
                return ResourceManager.GetString("MovePreviewWindowHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Post に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostContent {
            get {
                return ResourceManager.GetString("PostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POSTキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostKey {
            get {
                return ResourceManager.GetString("PostKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RestoreDefaultConfig {
            get {
                return ResourceManager.GetString("RestoreDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハッシュタグ ON/OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToggleHashtag {
            get {
                return ResourceManager.GetString("ToggleHashtag", resourceCulture);
            }
        }
    }
}
