//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kzrnm.WindowScreenshot.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kzrnm.WindowScreenshot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードにコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KindOfImage {
            get {
                return ResourceManager.GetString("KindOfImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   px に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string px {
            get {
                return ResourceManager.GetString("px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のプロセスを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectCaptureProcess {
            get {
                return ResourceManager.GetString("SelectCaptureProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   比率で指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingByPercentage {
            get {
                return ResourceManager.GetString("SettingByPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピクセル数で指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingByPixel {
            get {
                return ResourceManager.GetString("SettingByPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイドカットモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SideCutMode {
            get {
                return ResourceManager.GetString("SideCutMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
